apiVersion: v1
kind: Namespace
metadata:
  name:  qa
  labels:
    name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: qa
spec:
  hard:
    pods: '2'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-qa
  namespace: qa
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine