apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: nginx:alpine
    volumeMounts:
    - name: vol
      mountPath: /var/log/nginx
  volumes:
    - name: vol
      emptyDir: {}
        