apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    vol: test
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/test"
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  selector:
    matchLabels:
      vol: test
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi