apiVersion: v1
kind: Namespace
metadata:
  name:  default-resource-ns
  labels:
    name:  default-resource-ns
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
  namespace: default-resource-ns
spec:
  limits:
  - type: Container
    default:
      cpu: 300m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest
  namespace: default-resource-ns
  labels:
    app: podtest
spec:
  containers:
  - name: pod1
    image: nginx:alpine