apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-cpu
spec:
  containers:
  - name: pod-limit-cpu
    image: vish/stress
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.25"
    args:
      - -cpus
      - "2"