apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-ram
spec:
  containers:
  - name: pod-limit-ram
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]