apiVersion: v1
kind: Pod
metadata:
  name: pod-out-of-ram
spec:
  containers:
  - name: pod-out-of-ram
    image: polinux/stress
    resources:
      limits:
        memory: "1000Gi"
      requests:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]