apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cm-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: ["get", "watch", "list", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configMaps
  namespace: default
subjects:
- kind: User
  name: santiago
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cm-role
  apiGroup: rbac.authorization.k8s.io