apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: USER
  password: PASSWORD
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: secret-env-pod
    image: nginx:alpine
    env:
    - name: VOL_USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: VOL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    volumeMounts:
    - name: secret-vol-env
      mountPath: "/opt"
  volumes:
    - name: secret-vol-env
      secret:
        secretName: mysecret
        items:
          - key: username
            path: user.txt
