apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:               #Con Data hace falta pasar los values codificado en base64
  username: YWRtaW4=            
  password: MWYyZDFlMmU2N2Rm